import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

/**
 * Logs data from arrays to class (to be read by talon)
 * 
 * @author tedlin
 *
 */

public class TalonMPLogger {

    private static ArrayList<Double> m_position;
    private static ArrayList<Double> m_velocity;
    private static double m_clk;
    private static double m_dist;

    public TalonMPLogger(ArrayList<Double> position, ArrayList<Double> velocity, double clk, double dist) {
	m_position = position;
	m_velocity = velocity;
	m_clk = clk;
	m_dist = dist;
    }

    public void logData() {
	int maxIterations = m_position.size();

	FileWriter writer;
	try {
	    writer = new FileWriter("generated_profiles/" + "GeneratedTalonMP.java");
	    writer.append("/**" + '\n' + " * Generated by the TalonMPLogger in TalonTrapezoidal mode" + '\n' + " */"
		    + '\n' + '\n');

	    writer.append("public class GeneratedTalonMP {" + '\n' + '\n' + '\t');
	    writer.append("public static final int kNumPoints = " + maxIterations + ";" + '\n' + '\n' + '\t');
	    writer.append("// Position (rotations)	Velocity (RPM)	Duration (ms)" + '\n' + '\t');
	    writer.append("public static double [][]Points = new double[][]{" + '\n');

	    for (int j = 0; j < maxIterations - 1; j++) {
		writer.append("\t\t" + "{");
		writer.append(String.valueOf(m_position.get(j)));
		writer.append(",");
		writer.append(String.valueOf(m_velocity.get(j)));
		writer.append(",");
		writer.append(String.valueOf(m_clk));
		writer.append("},");
		writer.append('\n');
	    }

	    writer.append("\t\t" + "{");
	    writer.append(String.valueOf(m_dist));
	    writer.append(",");
	    writer.append("0");
	    writer.append(",");
	    writer.append(String.valueOf(m_clk));
	    writer.append("}");
	    writer.append("\r");

	    writer.append("\n\t" + "};");
	    writer.append('\n' + "}");
	    writer.flush();
	    writer.close();

	} catch (IOException e) {
	    e.printStackTrace();
	}
    }
}
